name: Build Image

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  NGINX_VERSION: 1.20

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        repository: zooniverse/docker-nginx

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/zooniverse/docker-nginx:$NGINX_VERSION,ghcr.io/zooniverse/docker-nginx:latest
        build-args: |
          VERSION=$NGINX_VERSION
        cache-from: type=gha
        cache-to: type=gha,mode=max
